name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  clang_format:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6

    - run: make -f utils.mk format

    - run: git diff --exit-code
