name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang_format:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v5

    - run: make -f utils.mk format

    - run: git diff --exit-code
